package codes.thischwa.bacoma.rest.service;

import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import codes.thischwa.bacoma.rest.model.pojo.site.Content;
import codes.thischwa.bacoma.rest.model.pojo.site.Level;
import codes.thischwa.bacoma.rest.model.pojo.site.Page;
import codes.thischwa.bacoma.rest.model.pojo.site.Site;
import codes.thischwa.bacoma.rest.model.pojo.site.Template;
import codes.thischwa.bacoma.rest.model.pojo.site.TemplateType;

public class _SiteBuilder {

	public _SiteBuilder(File jsonFile) throws IOException {
		Persister persister  = new Persister();
		Site site = new Site();
		site.setId(UUID.fromString("d20e9e25-7e34-4411-a70e-90104b8d6000"));
		site.setUrl("site.test");
		site.setTitle("A Test Site");
		site.setPages(Arrays.asList(new Page[]{buildPage("db47c9ac-3796-435d-ba15-fac8bf64deaf", "707cc97a-b1a3-4278-bce5-acd3874ba527", "frontpage", "welcome", "<h1>This is the welcome page&nbsp;...</h1><p>... of the site object!</p>")}));
		site.setLayoutTemplate(buildLayoutTemplate());
		site.setConfiguration(buildConfig());
		site.addTemplate(buildPageTemplate());
		
		Level lev_1 = buildLevel("d20e9e25-7e34-4411-a70e-90104b8d6001", site, "1_level", "1st Level");
		site.add(lev_1);
		lev_1.add(buildPage("d20e9e25-7e34-4411-a70e-90104b8d6010", "707cc97a-b1a3-4278-bce5-acd3874ba527", "frontpage", "welcome", "<h1>This is the welcome page&nbsp;...</h1><p>... of the site object!</p>"));
		Level lev_2 = buildLevel("d20e9e25-7e34-4411-a70e-90104b8d6002", site, "2_level", "2nd Level");
		site.add(lev_2);
		Level lev_2_1 = buildLevel("d20e9e25-7e34-4411-a70e-90104b8d6003", site, "2_1_level", "1st sub-level of the 2nd Level");
		lev_2.add(lev_2_1);
		
		persister.persist(jsonFile, site);
	}
	
	private Level buildLevel(String id, Level parent, String name, String title) {
		Level l = new Level();
		l.setId(UUID.fromString(id));
		l.setName(name);
		l.setTitle(title);
		return l;
	}
	
	private Page buildPage(String id, String templateID, String name, String title, String content) {
		Content c = new Content();
		c.setValue(content);
		Page page = new Page();
		page.setId(UUID.fromString(id));
		page.setName(name);
		page.setTitle(title);
		page.setContent(Arrays.asList(new Content[]{c}));
		page.setTemplateID(UUID.fromString(templateID));
		return page;
	}
	
	private Template buildLayoutTemplate() {
		Template t = new Template();
		t.setId(UUID.fromString("f597e595-c1a5-406f-bf7d-467bbfe40631"));
		t.setType(TemplateType.LAYOUT);
		String text =
				"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n" + 
				"\n" + 
				"<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\">\n" + 
				"<head>\n" + 
				"  <title>Test!</title>\n" + 
				"  <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\n" + 
				"</head>\n" + 
				"\n" + 
				"<body>\n" + 
				"<div id=\"body\">\n" + 
				"<div id=\"nested\">\n" + 
				"<div id=\"header\">\n" + 
				"  <h1>This is the header.</h1>\n" + 
				"  <p>It is an uneditable text and is hard-coded in the layout.html.</p>\n" + 
				"</div>\n" + 
				"\n" + 
				"<!-- ********** begin content area ********** -->\n" + 
				"\n" + 
				"$content\n" + 
				"\n" + 
				"<!-- ********** end content area ********** -->\n" + 
				"\n" + 
				"<div id=\"footer\">\n" + 
				"  <p>generated by BaCoMa</p>\n" + 
				"</div>\n" + 
				"</div>\n" + 
				"</div>\n" + 
				"</body>\n" + 
				"</html>";
		t.setText(text);
		return t;
	}
	
	private Template buildPageTemplate() {
		Template t = new Template();
		t.setId(UUID.fromString("707cc97a-b1a3-4278-bce5-acd3874ba527"));
		t.setType(TemplateType.PAGE);
		t.setName("Page tamplate");
		String text = "#parse('content.vm')\n" + 
				"##parse('user_menu.vm')\n" + 
				"\n" + 
				"<div id=\"content\">\n" + 
				"  #contentview(\"field1\" 605 520)\n" + 
				"#pagemenu()\n" + 
				"</div>";
		t.setText(text);
		return t;
	}
	
	private Map<String, String> buildConfig() {
		Map<String, String> config = new HashMap<>();
		config.put("site.export.folder", "temp_export");
		return config;
	}
	
	public static void main(String[] args) throws Exception {
		new _SiteBuilder(new File("test_temp"));
	}
}
